In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("/content/Retail_Sales.csv")

In [8]:
#Load Retail_Sales.csv into a DataFrame named df. Display the first 5 rows and the last 5 rows.
print(df.head())
print("\n")
print(df.tail())

   OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
0  ORD1084   Sanjay    Male  Electronics  North         1   20507.70
1  ORD1080    Rahul    Male  Electronics   East         2    4631.95
2  ORD1089   Athira  Female      Grocery   West         6     352.60
3  ORD1036    Sreya  Female         Home   East         4    4582.04
4  ORD1050   Farhan    Male      Grocery   West         1     202.73

   Discount  Rating   OrderDate
0       7.0     5.0  2026-03-23
1      14.0     5.0  2026-02-11
2      12.0     3.0  2026-03-01
3       8.0     2.0  2026-03-08
4      12.0     5.0  2026-01-11


    OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
90  ORD1083    Kiran    Male         Home  North         3    2488.81
91  ORD1034    Remya  Female      Grocery  South         4     392.58
92  ORD1087   Midhun    Male  Electronics  South         2    9134.12
93  ORD1009   Gopika  Female      Grocery   West         1     164.47
94  ORD1081    Remya  Female     Clothing   East         4    1339.89

    Discount  Rating   OrderDate
90      16.0     5.0  2026-01-27
91       8.0     NaN  2026-04-22
92       4.0     3.0  2026-03-25
93       7.0     3.0  2026-03-03
94      13.0     2.0  2026-06-29

In [9]:
#Display one random row from the DataFrame, using a random seed of 1 so that the result is reproducible.
print(df.sample(n=1,random_state=1))

    OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
40  ORD1062    Sreya  Female  Electronics  North         2   10057.13

    Discount  Rating   OrderDate
40      14.0     4.0  2026-03-27

In [10]:
#State the number of rows and columns in the DataFrame, and list all column names.
print("Rows and columns :",df.shape)
print("list all column name :",df.columns)

Rows and columns : (95, 10)
list all column name : Index(['OrderID', 'Customer', 'Gender', 'Category', 'Region', 'Quantity',
       'UnitPrice', 'Discount', 'Rating', 'OrderDate'],
      dtype='object')

In [11]:
#Show the data type of every column and the concise summary of the DataFrame. Identify the columns that have fewer non-null values than the total number of rows.
print(df.dtypes)
print("\n")
print(df.info())
print("\n")
print(df.isnull().any())

OrderID       object
Customer      object
Gender        object
Category      object
Region        object
Quantity       int64
UnitPrice    float64
Discount     float64
Rating       float64
OrderDate     object
dtype: object


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    95 non-null     object
 1   Customer   95 non-null     object
 2   Gender     95 non-null     object
 3   Category   95 non-null     object
 4   Region     95 non-null     object
 5   Quantity   95 non-null     int64
 6   UnitPrice  95 non-null     float64
 7   Discount   89 non-null     float64
 8   Rating     86 non-null     float64
 9   OrderDate  95 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 7.6+ KB
None


OrderID      False
Customer     False
Gender       False
Category     False
Region       False
Quantity     False
UnitPrice    False
Discount      True
Rating        True
OrderDate    False
dtype: bool

In [12]:
#Generate the summary statistics for the numeric columns, and then for all columns including text columns.
print(df.describe())
print("\n")
print(df.describe(include='all'))

        Quantity     UnitPrice   Discount     Rating
count  95.000000     95.000000  89.000000  86.000000
mean    3.452632   4167.508211  11.269663   3.151163
std     6.105053   6163.461567   5.078395   1.459391
min     1.000000     46.080000   2.000000   1.000000
25%     1.000000    239.580000   7.000000   2.000000
50%     2.000000   1339.890000  11.000000   3.000000
75%     4.000000   4631.950000  14.000000   5.000000
max    60.000000  24239.260000  25.000000   5.000000


        OrderID Customer Gender Category Region   Quantity     UnitPrice  \
count        95       95     95       95     95  95.000000     95.000000
unique       90       29      2        4      4        NaN           NaN
top     ORD1080   Athira   Male  Grocery   East        NaN           NaN
freq          2        5     48       38     30        NaN           NaN
mean        NaN      NaN    NaN      NaN    NaN   3.452632   4167.508211
std         NaN      NaN    NaN      NaN    NaN   6.105053   6163.461567
min         NaN      NaN    NaN      NaN    NaN   1.000000     46.080000
25%         NaN      NaN    NaN      NaN    NaN   1.000000    239.580000
50%         NaN      NaN    NaN      NaN    NaN   2.000000   1339.890000
75%         NaN      NaN    NaN      NaN    NaN   4.000000   4631.950000
max         NaN      NaN    NaN      NaN    NaN  60.000000  24239.260000

         Discount     Rating   OrderDate
count   89.000000  86.000000          95
unique        NaN        NaN          67
top           NaN        NaN  2026-04-21
freq          NaN        NaN           3
mean    11.269663   3.151163         NaN
std      5.078395   1.459391         NaN
min      2.000000   1.000000         NaN
25%      7.000000   2.000000         NaN
50%     11.000000   3.000000         NaN
75%     14.000000   5.000000         NaN
max     25.000000   5.000000         NaN

In [13]:
#Find the mean, median and mode of Quantity. Compare the mean and the median and state what the comparison indicates about the distribution
print("mean",df["Quantity"].mean())
print("median",df["Quantity"].median())
print("mode",df["Quantity"].mode())

mean 3.4526315789473685
median 2.0
mode 0    1
Name: Quantity, dtype: int64

In [14]:
#Find the minimum, maximum and standard deviation of UnitPrice
print("minimum uniprice :",df['UnitPrice'].min())
print("maximum uniprice :",df['UnitPrice'].max())
print("standard deviation",df['UnitPrice'].std())

minimum uniprice : 46.08
maximum uniprice : 24239.26
standard deviation 6163.4615671521515

In [15]:
#Count the non-null values in every column of the DataFrame. Explain any differences you observe between columns. Then compute the total number of units sold
print("non null values in each columns")
print(df.count())

print("Total unit sold",df['Quantity'].sum())

non null values in each columns
OrderID      95
Customer     95
Gender       95
Category     95
Region       95
Quantity     95
UnitPrice    95
Discount     89
Rating       86
OrderDate    95
dtype: int64
Total unit sold 328

In [16]:
#For the Category column, list the unique values, the number of unique values, the count of each value and the percentage share of each value.
print("uniques of category")
print(df['Category'].unique())
print("number of unique category",df['Category'].nunique())
print("number of unique :",df['Category'].value_counts())
print("percentage :",df['Category'].value_counts(normalize=True)*100)

uniques of category
['Electronics' 'Grocery' 'Home' 'Clothing']
number of unique category 4
number of unique : Category
Grocery        38
Electronics    29
Clothing       17
Home           11
Name: count, dtype: int64
percentage : Category
Grocery        40.000000
Electronics    30.526316
Clothing       17.894737
Home           11.578947
Name: proportion, dtype: float64

In [17]:
#Repeat the analysis for the Region column. Identify the region with the most orders.
print("uniques of category")
print(df['Region'].unique())
print("number of unique category",df['Region'].nunique())
print("number of unique :",df['Region'].value_counts())
print("percentage :",df['Region'].value_counts(normalize=True)*100)

uniques of category
['North' 'East' 'West' 'South']
number of unique category 4
number of unique : Region
East     30
South    24
North    22
West     19
Name: count, dtype: int64
percentage : Region
East     31.578947
South    25.263158
North    23.157895
West     20.000000
Name: proportion, dtype: float64

In [18]:
#Count the missing values in each column, the total number of missing values, and the percentage of missing values in each column.
print("Missing value in each columns :")
print(df.isnull().sum())
print("total missing value :",df.isnull().sum().sum())
print("percentage of missing values :",(df.isnull().mean())*100)

Missing value in each columns :
OrderID      0
Customer     0
Gender       0
Category     0
Region       0
Quantity     0
UnitPrice    0
Discount     6
Rating       9
OrderDate    0
dtype: int64
total missing value : 15
percentage of missing values : OrderID      0.000000
Customer     0.000000
Gender       0.000000
Category     0.000000
Region       0.000000
Quantity     0.000000
UnitPrice    0.000000
Discount     6.315789
Rating       9.473684
OrderDate    0.000000
dtype: float64

In [19]:
print("missing value in each columns",df.dropna())
print("\n")
print(df.dropna().value_counts())

missing value in each columns     OrderID Customer  Gender     Category Region  Quantity  UnitPrice  \
0   ORD1084   Sanjay    Male  Electronics  North         1   20507.70
1   ORD1080    Rahul    Male  Electronics   East         2    4631.95
2   ORD1089   Athira  Female      Grocery   West         6     352.60
3   ORD1036    Sreya  Female         Home   East         4    4582.04
4   ORD1050   Farhan    Male      Grocery   West         1     202.73
..      ...      ...     ...          ...    ...       ...        ...
88  ORD1075   Athira  Female      Grocery  South         6     150.19
90  ORD1083    Kiran    Male         Home  North         3    2488.81
92  ORD1087   Midhun    Male  Electronics  South         2    9134.12
93  ORD1009   Gopika  Female      Grocery   West         1     164.47
94  ORD1081    Remya  Female     Clothing   East         4    1339.89

    Discount  Rating   OrderDate
0        7.0     5.0  2026-03-23
1       14.0     5.0  2026-02-11
2       12.0     3.0  2026-03-01
3        8.0     2.0  2026-03-08
4       12.0     5.0  2026-01-11
..       ...     ...         ...
88      17.0     3.0  2026-01-27
90      16.0     5.0  2026-01-27
92       4.0     3.0  2026-03-25
93       7.0     3.0  2026-03-03
94      13.0     2.0  2026-06-29

[80 rows x 10 columns]


OrderID  Customer  Gender  Category     Region  Quantity  UnitPrice  Discount  Rating  OrderDate
ORD1077  Arjun     Male    Grocery      West    6         137.52     12.0      4.0     2026-04-09    2
ORD1087  Midhun    Male    Electronics  South   2         9134.12    4.0       3.0     2026-03-25    2
ORD1080  Rahul     Male    Electronics  East    2         4631.95    14.0      5.0     2026-02-11    2
ORD1029  Lakshmi   Female  Electronics  East    1         2659.08    7.0       5.0     2026-04-21    2
ORD1007  Basil     Male    Grocery      South   3         69.92      16.0      5.0     2026-02-24    1
                                                                                                    ..
ORD1084  Sanjay    Male    Electronics  North   1         20507.70   7.0       5.0     2026-03-23    1
ORD1086  Sreya     Female  Grocery      East    6         228.99     22.0      2.0     2026-03-29    1
ORD1088  Manu      Male    Electronics  South   2         12667.99   14.0      2.0     2026-06-18    1
ORD1089  Athira    Female  Grocery      West    6         352.60     12.0      3.0     2026-03-01    1
ORD1090  Midhun    Male    Home         East    1         4680.32    7.0       3.0     2026-05-27    1
Name: count, Length: 76, dtype: int64

In [20]:
# Determine how many rows would be lost if every row containing a missing value were removed (do not modify df). Justify whether removal is an appropriate choice for this dataset.
missing_rows = df.isnull().any(axis=1).sum()
print("Rows that would be removed:", missing_rows)
print("Total Rows:", len(df))
print("Remaining Rows:", len(df) - missing_rows)

Rows that would be removed: 15
Total Rows: 95
Remaining Rows: 80

In [21]:
#Treat the missing values in Discount and Rating using methods you consider appropriate. Save the changes in df, confirm that no missing values remain, and justify your choice of method for each column.
df['Discount'] = df['Discount'].fillna(df['Discount'].median())
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

print("Missing Values After Treatment:")
print(df.isnull().sum())
print("Total Missing Values:", df.isnull().sum().sum())

Missing Values After Treatment:
OrderID      0
Customer     0
Gender       0
Category     0
Region       0
Quantity     0
UnitPrice    0
Discount     0
Rating       0
OrderDate    0
dtype: int64
Total Missing Values: 0

In [22]:
# Count the duplicate rows. Display every row that belongs to a duplicate group, including the first occurrence, sorted by OrderID.
print("Number of Duplicate Rows:", df.duplicated().sum())
duplicates = df[df.duplicated(keep=False)].sort_values('OrderID')

display(duplicates)

Number of Duplicate Rows: 5

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
24,ORD1029,Lakshmi,Female,Electronics,East,1,2659.08,7.0,5.0,2026-04-21
69,ORD1029,Lakshmi,Female,Electronics,East,1,2659.08,7.0,5.0,2026-04-21
68,ORD1034,Remya,Female,Grocery,South,4,392.58,8.0,3.0,2026-04-22
91,ORD1034,Remya,Female,Grocery,South,4,392.58,8.0,3.0,2026-04-22
45,ORD1077,Arjun,Male,Grocery,West,6,137.52,12.0,4.0,2026-04-09
47,ORD1077,Arjun,Male,Grocery,West,6,137.52,12.0,4.0,2026-04-09
1,ORD1080,Rahul,Male,Electronics,East,2,4631.95,14.0,5.0,2026-02-11
55,ORD1080,Rahul,Male,Electronics,East,2,4631.95,14.0,5.0,2026-02-11
58,ORD1087,Midhun,Male,Electronics,South,2,9134.12,4.0,3.0,2026-03-25
92,ORD1087,Midhun,Male,Electronics,South,2,9134.12,4.0,3.0,2026-03-25

In [23]:
 #Remove the duplicate records, save the result in df, and confirm the new shape of the DataFrame.
 df = df.drop_duplicates()

print("Shape After Removing Duplicates:")
print(df.shape)

Shape After Removing Duplicates:
(90, 10)

In [24]:
# OrderDate is stored as text. Convert it to a proper date data type. Some entries may not be valid dates; handle them so that the conversion does not fail, and report how many invalid dates were found.
df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors='coerce')
invalid_dates = df['OrderDate'].isnull().sum()
print("Invalid Dates:", invalid_dates)
print(df['OrderDate'].dtype)

Invalid Dates: 2
datetime64[ns]

In [25]:
 #Convert Category and Region to the string data type and Quantity to a floating-point type. Print the data types to verify.
 df['Category'] = df['Category'].astype('string')
df['Region'] = df['Region'].astype('string')
df['Quantity'] = df['Quantity'].astype(float)

print(df.dtypes)

OrderID              object
Customer             object
Gender               object
Category     string[python]
Region       string[python]
Quantity            float64
UnitPrice           float64
Discount            float64
Rating              float64
OrderDate    datetime64[ns]
dtype: object

In [26]:
#  Create the DataFrame below, in which Age is stored as text. Convert Age to integers. Then take a column that contains the text 'abc' among numeric strings and convert it to numeric without the program raising an error. Explain the difference in behaviour between the two conversion approaches you used.	[3]
#small = pd.DataFrame({'Name':['Anu','Rahul','Meera'], 'Age':['20','21','22']})
small = pd.DataFrame({
    'Name': ['Anu', 'Rahul', 'Meera'],
    'Age': ['20', '21', '22']
})

small['Age'] = small['Age'].astype(int)
display(small)
data = pd.Series(['10', '20', 'abc', '30'])
data = pd.to_numeric(data, errors='coerce')

print(data)

    Name  Age
0    Anu   20
1  Rahul   21
2  Meera   22

0    10.0
1    20.0
2     NaN
3    30.0
dtype: float64

In [27]:
#Show all orders where Quantity is greater than 5.
display(df[df['Quantity'] > 5])

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
2,ORD1089,Athira,Female,Grocery,West,6.0,352.60,12.0,3.0,2026-03-01
18,ORD1005,Manu,Male,Grocery,South,6.0,239.34,22.0,3.0,2026-06-28
33,ORD1028,Neha,Female,Clothing,East,6.0,480.23,17.0,5.0,2026-06-25
35,ORD1042,Joseph,Male,Grocery,East,6.0,262.10,12.0,3.0,2026-02-20
41,ORD1027,Arjun,Male,Grocery,West,6.0,71.02,22.0,3.0,2026-05-04
45,ORD1077,Arjun,Male,Grocery,West,6.0,137.52,12.0,4.0,2026-04-09
63,ORD1002,Neha,Female,Grocery,East,6.0,86.72,22.0,5.0,2026-06-27
65,ORD1086,Sreya,Female,Grocery,East,6.0,228.99,22.0,2.0,2026-03-29
75,ORD1018,Basil,Male,Grocery,South,60.0,120.00,25.0,1.0,2026-04-07
80,ORD1054,Divya,Female,Home,South,6.0,3645.08,12.0,4.0,2026-01-10
88,ORD1075,Athira,Female,Grocery,South,6.0,150.19,17.0,3.0,2026-01-27

In [28]:
#Show all orders where Rating is below 3, displaying only the columns OrderID, Category and Rating.
display(df.loc[df['Rating'] < 3, ['OrderID', 'Category', 'Rating']])

    OrderID     Category  Rating
3   ORD1036         Home     2.0
8   ORD1060  Electronics     2.0
10  ORD1068     Clothing     2.0
11  ORD1076      Grocery     1.0
12  ORD1056  Electronics     1.0
14  ORD1011     Clothing     1.0
16  ORD1070         Home     1.0
17  ORD1003  Electronics     2.0
20  ORD1012      Grocery     1.0
27  ORD1032      Grocery     2.0
29  ORD1015      Grocery     1.0
32  ORD1013         Home     1.0
36  ORD1001  Electronics     1.0
37  ORD1026  Electronics     2.0
38  ORD1088  Electronics     2.0
39  ORD1055      Grocery     2.0
42  ORD1020     Clothing     1.0
43  ORD1031  Electronics     2.0
49  ORD1016  Electronics     2.0
50  ORD1037     Clothing     1.0
53  ORD1065      Grocery     2.0
54  ORD1072     Clothing     2.0
59  ORD1040  Electronics     1.0
64  ORD1052      Grocery     1.0
65  ORD1086      Grocery     2.0
67  ORD1046  Electronics     2.0
71  ORD1058  Electronics     1.0
75  ORD1018      Grocery     1.0
77  ORD1017         Home     2.0
82  ORD1061     Clothing     1.0
83  ORD1057         Home     2.0
94  ORD1081     Clothing     2.0

In [29]:
#Sort all orders by UnitPrice from highest to lowest and display the top 5 rows.
display(df.sort_values(by='UnitPrice', ascending=False).head(5))

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
12,ORD1056,Ajith,Male,Electronics,South,2.0,24239.26,14.0,1.0,2026-02-14
51,ORD1059,Basil,Male,Electronics,West,2.0,22650.65,11.0,5.0,2026-03-03
59,ORD1040,Midhun,Male,Electronics,West,2.0,22211.38,9.0,1.0,2026-04-02
49,ORD1016,Keerthi,Female,Electronics,South,2.0,21543.62,14.0,2.0,2026-02-14
0,ORD1084,Sanjay,Male,Electronics,North,1.0,20507.70,7.0,5.0,2026-03-23

In [30]:
#Without sorting the entire DataFrame, find the 5 orders with the highest Quantity.
display(df.nlargest(5, 'Quantity'))

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
75,ORD1018,Basil,Male,Grocery,South,60.0,120.00,25.0,1.0,2026-04-07
2,ORD1089,Athira,Female,Grocery,West,6.0,352.60,12.0,3.0,2026-03-01
18,ORD1005,Manu,Male,Grocery,South,6.0,239.34,22.0,3.0,2026-06-28
33,ORD1028,Neha,Female,Clothing,East,6.0,480.23,17.0,5.0,2026-06-25
35,ORD1042,Joseph,Male,Grocery,East,6.0,262.10,12.0,3.0,2026-02-20

In [31]:
#  For each Category, show the count, mean, median, minimum and maximum of UnitPrice in a single table.
print(df.groupby('Category')['Quantity'].mean())

Category
Clothing       3.294118
Electronics    1.615385
Grocery        5.055556
Home           3.000000
Name: Quantity, dtype: float64

In [32]:
#Find the average Rating for each Region and for each Gender. State which region is rated best
price_summary = df.groupby('Category')['UnitPrice'].agg(
    ['count', 'mean', 'median', 'min', 'max'])

display(price_summary)

             count          mean    median      min       max
Category
Clothing        17   1425.132941   1339.89   431.57   2885.12
Electronics     26  11801.389615  10543.32  2659.08  24239.26
Grocery         36    196.371944    191.40    46.08    392.58
Home            11   3711.386364   3645.08   942.68   5657.83

In [33]:
# Find the correlation between Quantity and Discount, and between UnitPrice and Rating. State which relationship is stronger and give a possible reason.
print("Average Rating by Region:")
region_rating = df.groupby('Region')['Rating'].mean()
print(region_rating)
print("Best Rated Region:", region_rating.idxmax())
print("Average Rating by Gender:")
print(df.groupby('Gender')['Rating'].mean())

Average Rating by Region:
Region
East     3.107143
North    3.318182
South    2.727273
West     3.222222
Name: Rating, dtype: float64
Best Rated Region: North
Average Rating by Gender:
Gender
Female    3.000000
Male      3.177778
Name: Rating, dtype: float64

In [37]:
#Use the Interquartile Range (IQR) method to identify outliers in Quantity. Print Q1, Q3, the lower and upper limits, and the outlier rows.
correlation = df[['Quantity', 'Discount', 'UnitPrice', 'Rating']].corr()
print("Correlation Matrix:")
display(correlation)
print("Quantity and Discount Correlation:",correlation.loc['Quantity', 'Discount'])
print("UnitPrice and Rating Correlation:",correlation.loc['UnitPrice', 'Rating'])

Correlation Matrix:

           Quantity  Discount  UnitPrice    Rating
Quantity   1.000000  0.453408  -0.169728 -0.164448
Discount   0.453408  1.000000  -0.155276 -0.058619
UnitPrice -0.169728 -0.155276   1.000000 -0.082774
Rating    -0.164448 -0.058619  -0.082774  1.000000

Quantity and Discount Correlation: 0.4534077017787752
UnitPrice and Rating Correlation: -0.08277441287112026

In [41]:
#Examine the outlier rows and decide whether they are genuine or data-entry errors, giving your reasoning. Create a DataFrame named df_clean that excludes the rows you judge to be errors, and compare the mean of Quantity before and after.
Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
outliers = df[(df['Quantity'] < lower_limit) |(df['Quantity'] > upper_limit)]
display(outliers)

Q1: 1.0
Q3: 4.0
IQR: 3.0
Lower Limit: -3.5
Upper Limit: 8.5

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate
75,ORD1018,Basil,Male,Grocery,South,60.0,120.0,25.0,1.0,2026-04-07

In [40]:
#Examine the outlier rows and decide whether they are genuine or data-entry errors, giving your reasoning. Create a DataFrame named df_clean that excludes the rows you judge to be errors, and compare the mean of Quantity before and after.
df_clean = df[
    (df['Quantity'] >= lower_limit) &
    (df['Quantity'] <= upper_limit)].copy()

print("Mean Before Removing Outliers:", df['Quantity'].mean())
print("Mean After Removing Outliers:", df_clean['Quantity'].mean())
print("Shape Before:", df.shape)
print("Shape After:", df_clean.shape)

Mean Before Removing Outliers: 3.477777777777778
Mean After Removing Outliers: 2.842696629213483
Shape Before: (90, 10)
Shape After: (89, 10)

In [42]:
# Use df_clean from this point onwards. Create a column Gross (Quantity x UnitPrice) and a column Revenue, which is Gross after applying the Discount percentage.
df_clean['Gross'] = df_clean['Quantity'] * df_clean['UnitPrice']
df_clean['Revenue'] = (df_clean['Gross'] * (1 - df_clean['Discount'] / 100))
display(df_clean[['OrderID', 'Gross', 'Revenue']])

    OrderID     Gross     Revenue
0   ORD1084  20507.70  19072.1610
1   ORD1080   9263.90   7966.9540
2   ORD1089   2115.60   1861.7280
3   ORD1036  18328.16  16861.9072
4   ORD1050    202.73    178.4024
..      ...       ...         ...
88  ORD1075    901.14    747.9462
89  ORD1082   8482.35   7125.1740
90  ORD1083   7466.43   6271.8012
93  ORD1009    164.47    152.9571
94  ORD1081   5359.56   4662.8172

[89 rows x 3 columns]

In [43]:
#Create a column Order_Size classifying each order as 'Large' if Revenue is at least 10000, 'Medium' if Revenue is at least 2000 but below 10000, and 'Small' otherwise. Count the orders in each size class.
df_clean['Order_Size'] = df_clean['Revenue'].apply(
    lambda x: 'Large' if x >= 10000
    else 'Medium' if x >= 2000
    else 'Small')

print("Orders in Each Size Class:")
print(df_clean['Order_Size'].value_counts())

Orders in Each Size Class:
Order_Size
Small     40
Medium    25
Large     24
Name: count, dtype: int64

In [44]:
#  Find the top 5 orders by Revenue and the total Revenue for each Category.
print("Top 5 Orders by Revenue:")
display(df_clean.nlargest(5, 'Revenue'))

print("Total Revenue for Each Category:")
category_revenue = df_clean.groupby('Category')['Revenue'].sum()
print(category_revenue)

Top 5 Orders by Revenue:

,OrderID,Customer,Gender,Category,Region,Quantity,UnitPrice,Discount,Rating,OrderDate,Gross,Revenue,Order_Size
12,ORD1056,Ajith,Male,Electronics,South,2.0,24239.26,14.0,1.0,2026-02-14,48478.52,41691.5272,Large
59,ORD1040,Midhun,Male,Electronics,West,2.0,22211.38,9.0,1.0,2026-04-02,44422.76,40424.7116,Large
51,ORD1059,Basil,Male,Electronics,West,2.0,22650.65,11.0,5.0,2026-03-03,45301.30,40318.1570,Large
49,ORD1016,Keerthi,Female,Electronics,South,2.0,21543.62,14.0,2.0,2026-02-14,43087.24,37055.0264,Large
8,ORD1060,Keerthi,Female,Electronics,South,2.0,13809.19,9.0,2.0,2026-04-16,27618.38,25132.7258,Large

Total Revenue for Each Category:
Category
Clothing        73528.9599
Electronics    442776.7851
Grocery         20319.6622
Home           100989.4981
Name: Revenue, dtype: float64

In [45]:
#Save df_clean as cleaned_retail.csv without the index column. Reload the file and print its shape to verify.
df_clean.to_csv('cleaned_retail.csv', index=False)
reloaded_df = pd.read_csv('cleaned_retail.csv')

print("Reloaded DataFrame Shape:")
print(reloaded_df.shape)

Reloaded DataFrame Shape:
(89, 13)

In [48]:
#Which Category brings the highest total Revenue, and which Region sells the most?
category_revenue = df_clean.groupby('Category')['Revenue'].sum()
print("Category with Highest Revenue:",category_revenue.idxmax())
print("Highest Category Revenue:",category_revenue.max())
region_revenue = df_clean.groupby('Region')['Revenue'].sum()
print("Region with Highest Revenue:",region_revenue.idxmax())
print("Highest Region Revenue:",region_revenue.max())

Category with Highest Revenue: Electronics
Highest Category Revenue: 442776.7851
Region with Highest Revenue: South
Highest Region Revenue: 226489.8033

In [49]:
# Does a higher Discount appear to increase the Quantity bought? Support your answer with a numerical value from your analysis.
correlation = df_clean['Quantity'].corr(df_clean['Discount'])
print("Correlation between Quantity and Discount:", correlation)

Correlation between Quantity and Discount: 0.6601101948303969